services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    command: 
      - --default-time-zone=-03:00
      - --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wwwolima_yerbalito
      MYSQL_USER: wwwolima
      MYSQL_PASSWORD: rjW63u0I6n
      TZ: America/Montevideo
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/wwwolima_yerbalito-3.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: node:18-alpine
    container_name: yerbalito_backend
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=mysql_container
      - MYSQL_USER=wwwolima
      - MYSQL_PASSWORD=rjW63u0I6n
      - MYSQL_DATABASE=wwwolima_yerbalito
      - PORT=5001
      - TZ=America/Montevideo
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    image: node:18-alpine
    container_name: yerbalito_frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5001
    ports:
      - "8082:5173"
    volumes:
      - ./yerbalito:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:


